# This docker-compose file contains an example on how to build and run an ISG

version: '2.4'

services:
  isg:
    environment:
      - ICONIK_URL
      - AUTH_TOKEN
      - APP_ID
      - STORAGE_ID
    build:
      context: .
      # Uncomment the following lines to build an image with a development ISG
      # args:
      #   REPO_BASE: https://packages.iconik.io/dev/deb/ubuntu
    volumes:
      # This is the ISG data directory where the local database is kept.
      - ./isg_local_data:/var/iconik/iconik_storage_gateway/data

      # Uncomment the following line to map a media volume into the ISG container
      # - /Volumes/example:/Volumes/example
    